### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by MasterProgs** [alfianpr/tiktokshop-scraper#2]
Hello which Android Image do you use ? (SDKManager)
Which APK, cuz it seems that tiktok APK run only on ARM64 devices.
So how did you run the apk on emulator amd64 ?

Thank you

**Comment by alfianpr** [comment]
Hi, I'm using a real android device, but if you want to use an emulator. You could use genymotion and install [ARM translation](https://github.com/m9rco/Genymotion_ARM_Translation)  or use the Playstore version image if you want to use Android Studio Emulator. But in my case, I have an issue, the shop menu disappears, so I'm using a real device.
